### ISSUE TITLE
Fix User Story Names

### ISSUE THREAD

**Issue by Wmaxlees** [acm-ucdenver/website#105]
As a dev, I would like clearer user story names.

**Comment by Wmaxlees** [comment]
Prototype:
`{server/site/planning/other} - {type} - 3 word description - ###`

???

**Comment by robfitzgerald** [comment]
What if we rewrite our tags to be server/site/planning/other? As in the colored tags that can be applied to user stories.

**Comment by robfitzgerald** [comment]
Leaving only <type> <description>, such as "articles - angular service" or "server environment

**Comment by robfitzgerald** [comment]
Ack close button right next to keyboard shortcuts on my Android...

**Comment by Wmaxlees** [comment]
Well, I think our tags are already pretty solid as far as keywords. Server, website, etc. covers the first piece. Articles, Events, etc. covers the second piece. I personally would just like a 3-5 word description. I added the first couple pieces because you mentioned you thought it would be a good idea.

**Comment by robfitzgerald** [comment]
Yea but I agree with you, just more of a plain English description would be more ideal, and then combined with more readable titles, I might start connecting the titles and tags with greater readability.

**Comment by robfitzgerald** [comment]
Let's also use this opportunity to consolidate any unassigned dev tasks which have too low of a scope, if any still remain (such as rolling separate GET, PUT, POST, DELETE stories into one)

**Comment by Wmaxlees** [comment]
Good idea

**Comment by robfitzgerald** [comment]
i rewrote the tags.  also had a little fun choosing story points for this sprint.

**Comment by robfitzgerald** [comment]
there seems to be a little lag with zenhub updating all of the tag changes, or, there are conflicts (names not changed and colors not changed for some instances).  i'll wait and see if it fixes itself.
