### ISSUE TITLE
Server location

### ISSUE THREAD

**Issue by robfitzgerald** [acm-ucdenver/website#58]
As a web developer, I would like to know the location of the server where the production environment lives, and how to access that server.

**Comment by robfitzgerald** [comment]
questions i posed to Dat (SysAdmin @ CSE):
>A few questions.
>
>1) Will we be able to install node.js and MongoDB on this server (given command line access and the >ability to install node.js, git, and some other applications)?
>
>Will we be able to access SMTP (campus or our own)?  We want to have a landing page for local >companies, and we want to allow those companies to contact us with a simple web form that will send >us their message to our email inboxes.  So, not for making some crazy spam list ;-)

response from dat:
>Grab me this summer when I am back in Denver and we can talk about setting these things up…

sweet.  so, in the meantime, I made a digital ocean droplet that we can use for server space.  I can pass those credentials to anyone via email.

**Comment by robfitzgerald** [comment]
we can call this droplet our dev environment if we want to be super pro, and make the prod environment be the ~acm site at cse.  we can constantly code to the droplet site, and then plan deployments to the prod environment with tested code in controlled increments.  if so, we can make a wiki page with the following:

```
Server Information
'dev' - Development Environment
URL: http://45.55.225.76​
'prod' - Production Environment
URL: http://cse.ucdenver.edu/~acm/
credentials available by email with ACM officers.
```

**Comment by robfitzgerald** [comment]
btw the droplet isn't set up to http to it yet, so that link won't work.  :-P

**Comment by Wmaxlees** [comment]
When does Dat get back?

**Comment by robfitzgerald** [comment]
early june

**Comment by robfitzgerald** [comment]
emailed dat.

**Comment by robfitzgerald** [comment]
visited dat today.  this issue hasn't budged, he says he was too busy to look at it last week.  i'll check in again in a week.

**Comment by robfitzgerald** [comment]
did NOT catch dat today, he was busy.  i'll try again on wednesday.

**Comment by robfitzgerald** [comment]
UPDATE!  Dat has installed MongoDB on the server.  He asked us to try it out.  So, I did.  It didn't work.  I think the service isn't running, and on RedHat, I think there is some additional config and some super user stuff that needs to happen.  I sent him some documentation.

**Comment by Wmaxlees** [comment]
That's good news. Things are in progress

**Comment by robfitzgerald** [comment]
new email to Dat sent, asking for what's up, and showing him the dev server, and asking if i can help.

**Comment by robfitzgerald** [comment]
mongodb is running on the school server!  woO HHOOOO!
so next up is just being sure that we can manage our express server's process, and be able to turn it off and on.  i made note of this elsewhere, but, @Wmaxlees, do you know how we can do that?

**Comment by robfitzgerald** [comment]
i'm assuming this involves npm's forever.  but even then, we need to be sure we have the permissions to close a process by PID.

**Comment by Wmaxlees** [comment]
I've been using `npm start > node.log &` on the test server. Since we are starting the process, we own it. So we'll be able to kill it as well. That command won't restart the server if it crashes, though. Maybe we make a user story for finding a solution to that (or we may already have one)

**Comment by robfitzgerald** [comment]
oh right, redirect the output of the process to a file.  and, we can manage the process === we've got everything we need.  this user story is closed, ya?
