### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by Wmaxlees** [acm-ucdenver/website#79]
As a developer, I need a 'project' object schematic and an updated wiki that contains information about the new page

**Comment by Wmaxlees** [comment]
I'll take a stab at this

```
{
    "title": "Name of the project",
    "desc": "Description of project",
    "date": Date,
    "contr":
    [
            { "name": "Name of contributor" },
            ...
    ],
    "links":
    [
            {
                "text": "Link text",
                "url": "Link target"
            },
            ...
    ],
    "tags":
    [
            { "tag": "Tech tag (ie Node.js or Java)" },
            ...
    ]
}
```

Too complicated? I think all the info would be nice to have.

**Comment by Wmaxlees** [comment]
[Here is the wiki](https://github.com/amc-ucdenver/website/wiki/Project-Schema). Just need a confirmation from @robfitzgerald

**Comment by robfitzgerald** [comment]
that schema is hot.
