### ISSUE TITLE
Member Schema - 001

### ISSUE THREAD

**Issue by Wmaxlees** [acm-ucdenver/website#81]
As a developer, I need to know what the member email schema looks like

**Comment by Wmaxlees** [comment]
```
{
  "email": "email@address.com",
  "name": "Real Name",
  "email verified": Date()
}
```

Credit goes to @robfitzgerald for this.

**Comment by Wmaxlees** [comment]
[Here is the wiki](https://github.com/amc-ucdenver/website/wiki/Member-Schema). Just need a confirmation from @robfitzgerald

**Comment by robfitzgerald** [comment]
did i do that?  :+1:
